### ISSUE TITLE
Help: Extract stpp (ttml) codec within mp4 dash

### ISSUE THREAD

**Issue by pandamoon21** [xhlove/dash-mp4-vtt-extractor#1]
Hi, I just found a website that uses this codec in the dash manifest.
```
AdaptationSet mimeType="application/mp4" codecs="stpp"
```
I've managed to get the mp4 file with your mpd-content-parser and merge it into a file. I tried to extract the subtitle using this but not get a result.
```
no vtt subtitle was founded TAT.
vtt file path is C:\Users\dash-mp4-vtt-extractor-master\sample.vtt
0 lines of vtt subtitles were founded. (*^▽^*)
```
Can you help me to check it please? (timescale = 9000)
Here the mp4 dash file, https://files.catbox.moe/stdaqa.mp4

**Comment by pandamoon21** [comment]
I've figured it out now. Thanks. :)

**Comment by dausruddin** [comment]
Hi. How did you solved it? Because I am in the same position.

Thank you!

**Comment by xbstory** [comment]
can you provide mpd link or downloaded files (zip) with out merge, now I am testing for ttml
