### ISSUE TITLE
你好，如下：

### ISSUE THREAD

**Issue by xiaoxiaoliya** [xhlove/dash-mp4-vtt-extractor#3]
[dash_subtitle_WVTT_zh-TW.zip](https://github.com/xhlove/dash-subtitle-extractor/files/8886303/dash_subtitle_WVTT_zh-TW.zip)
[dash_subtitle_WVTT_en.zip](https://github.com/xhlove/dash-subtitle-extractor/files/8886304/dash_subtitle_WVTT_en.zip)
![image](https://user-images.githubusercontent.com/94291982/173244186-e19f3d54-6102-4c3a-aaf4-ff56cb983f0c.png)
尝试合并的时候出现这个错误

**Comment by xiaoxiaoliya** [comment]
[pyshaka.zip](https://github.com/xhlove/dash-subtitle-extractor/files/8887203/pyshaka.zip)

**Comment by xbstory** [comment]
fixed

**Comment by xiaoxiaoliya** [comment]
> fixed

非常感谢
