### ISSUE TITLE
Error: settings = ' ' + settings

### ISSUE THREAD

**Issue by VCDEV1** [xhlove/dash-mp4-vtt-extractor#4]
Hi, First of all thank you for this amazing tool!

This worked with almost all dash subtitles I have encountered! But with this one subtitle it seems to have some error.

The mpd link of the dash subtitle I am trying to download is: https://streaming-vod-aha.akamaized.net/content/pubcontent/vol/AC132CEE-A998-4DB7-93F9-7EE2AFE5AA56/1656584319882-output_cenc_dash.ism/index.mpd?pipeline=ttml_removal&filter=%28%28type%3D%3D%22video%22%26%26FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C%3D1500000%29%7C%7C%28type%3D%3D%22audio%22%26%26FourCC%3D%3D%22AACL%22%29%7C%7C%28type%3D%3D%22textstream%22%29%29 (Link is still valid)

**I tried this with two methods.**

1. By making a folder (after splitting the mp4 container) with the init file and the segments. I tried with both ttml and wvtt formats. The result is shown below.

![image](https://user-images.githubusercontent.com/81463419/180317675-9cb8bda2-468e-4986-98cd-b2b8e19ecaac.png)

2. By making a folder only with the init and the mp4 container (without splitting the mp4 container). I again tried with both of the ttml and wvtt formats but still an error message was shown. But this time the error messages were different a little. The result is shown below.

![image](https://user-images.githubusercontent.com/81463419/180318416-36672ecf-0cbe-44e4-b5ac-d63ffec5c51a.png)

I was using the latest code and the files I used will be attached below!

[aha-with-segments.zip](https://github.com/xhlove/dash-subtitle-extractor/files/9162914/aha-with-segments.zip)
[aha-with-mp4-container.zip](https://github.com/xhlove/dash-subtitle-extractor/files/9162915/aha-with-mp4-container.zip)

If you can look into this and maybe add support for this it will be really helpful. Thanks.

**Comment by xbstory** [comment]
thank you for your feedback, fixed !

**Comment by VCDEV1** [comment]
Thank you so much! It works. Thanks again!
